name: inid_assistant
description: Iranian National ID Card Reader
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.3.1
  x509: ^0.2.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  share_plus: ^7.1.0
  ndef: ^0.3.4
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
